### ISSUE TITLE
Start on Mini-Golf Course?

### ISSUE THREAD

**Issue by LlanerasJ** [cop2805-bkj/Mini-Golf-Course#1]
We need to decide what were going to do for the golf course project. I don't know if maybe we can talk it over class tomorrow? It doesn't look to challenging we just we have to implement the code this time and write J Unit Tests as well. Also we need the RFP for the project as well. 

@Xinnx @DDKGM

**Comment by Nivirx** [comment]
I just read over the project page a few times...and I have no idea what the requirements are for this project. I think talking about it before/after class tomorrow would be a good plan.

**Comment by LlanerasJ** [comment]
Yeah I looked at it a couple of times as well and i couldn't figure it out either! So ill just see you at class tonight!
