### ISSUE TITLE
Project 8 (Mini-Golf Course)

### ISSUE THREAD

**Issue by DDKGM** [cop2805-bkj/Mini-Golf-Course#2]
Hello guys,

This is what I need from each of you to get this project done. I'll take care of the rest as far as writing and formatting the document. As you may already be aware this project is like the last one, were there will be no code written. This project is very small, and thus requires little to no effort. Your contributions are as follows:

Jonathan: Use-case 1 (Assign Card)
The user must go to the front counter and request/pay for a card. The card is then printed with the customers name.

Bradley: Use-case 2 (Score Tracking)
After completing each hole, the user swipes their card at the hole's swipe station, and enters the number of strokes. The station displays the players name and current score.

If you aren't sure how to write a Use Case, simply look at our last project submission email to prof. Pollock. I  CC'ed you guys in it so you should be able to download it and look at it. Regardless, don't worry about making any mistakes, I'll clean it all up in the final document, and don't over think this. This project is truly that simple. After speaking with the prof. he even considered pulling it because of how stupid simple it is.

Please get this to me asap, I want to submit as soon as possible. Only one of us needs to submit so once I get your portions I will submit. You guys can send me your contributions on here or through email.

Best regards,

Kelvin Gomez

**Comment by Nivirx** [comment]
It says we can use UML, do I need to make a write up on score tracking or can I just make a UML diagram?

**Comment by DDKGM** [comment]
Neither. I'll take care of that. All I need from you is the Use Case.

**Comment by LlanerasJ** [comment]
Alright sounds good! Ill probably start on it over the weekend!

**Comment by Nivirx** [comment]
This is what I have so far, tell me if you want more changes.
[SwipeStationUsecases.docx](https://github.com/cop2805-bkj/Mini-Golf-Course/files/966369/SwipeStationUsecases.docx)

**Comment by DDKGM** [comment]
No, this is great. You're done. Thank you.

**Comment by LlanerasJ** [comment]
This is what I did i don't know what else i can do for just requesting a card and payment.
[User Cases MG Java Assignment.docx](https://github.com/cop2805-bkj/Mini-Golf-Course/files/966992/User.Cases.MG.Java.Assignment.docx)

**Comment by DDKGM** [comment]
That works. I'll be submitting shortly.
